
version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - gosec

formatters:
  enable:
    - gofmt
    - goimports
    - golines
