project_name: elb-trust-store-exporter

env:
  - GO11MODULE=on

before:
  hooks:
    - go mod download

builds:
  - main: main.go
    binary: "{{ .ProjectName }}"
    goos:
      - darwin
      - linux
      - freebsd
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

snapshot:
  name_template: "git-{{.ShortCommit}}"

# Push arch specific images (push is required for multi-arch manifests)
dockers:
  - image_templates:
      - "public.ecr.aws/panubo/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "quay.io/panubo/{{ .ProjectName }}:{{ .Version }}-amd64"
    use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "public.ecr.aws/panubo/{{ .ProjectName }}:{{ .Version }}-arm64"
      - "quay.io/panubo/{{ .ProjectName }}:{{ .Version }}-arm64"
    use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"

# Push multi-arch manifests
docker_manifests:
  # Docker Hub
  - name_template: "public.ecr.aws/panubo/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "public.ecr.aws/panubo/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "public.ecr.aws/panubo/{{ .ProjectName }}:{{ .Version }}-arm64"
  - name_template: "public.ecr.aws/panubo/{{ .ProjectName }}:{{.Major}}.{{.Minor}}"
    image_templates:
      - "public.ecr.aws/panubo/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "public.ecr.aws/panubo/{{ .ProjectName }}:{{ .Version }}-arm64"
  # Quay.io
  - name_template: "quay.io/panubo/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "quay.io/panubo/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "quay.io/panubo/{{ .ProjectName }}:{{ .Version }}-arm64"
  - name_template: "quay.io/panubo/{{ .ProjectName }}:{{.Major}}.{{.Minor}}"
    image_templates:
      - "quay.io/panubo/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "quay.io/panubo/{{ .ProjectName }}:{{ .Version }}-arm64"

release:
  github:
    owner: panubo
    name: "{{ .ProjectName }}"
  draft: false