name: build

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:

permissions:
  id-token: write   # Required for OIDC
  contents: write   # This is required for actions/checkout and creating releases
  actions: write    # Require to upload artifacts

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
         fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          install-only: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      # The values provided to these two AWS steps are always the same for Panubo owned repos
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Login to ECR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: public.ecr.aws

      - name: Login to Quay.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.PANUBUILD_QUAYIO_USERNAME }}
          password: ${{ secrets.PANUBUILD_QUAYIO_TOKEN }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # - name: Make test
      #   run: |
      #     make test

      - name: GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            goreleaser
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
            goreleaser --snapshot
          fi

      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*
